CREATE TABLE IF NOT EXISTS support_policy_versions (
  id uuid PRIMARY KEY,
  policy_version text NOT NULL UNIQUE,
  preset text NOT NULL CHECK (preset IN ('CONSERVATIVE','STANDARD','HIGH')),
  intent text NOT NULL,
  disposition text NOT NULL CHECK (disposition IN ('AUTO_RESOLVE','NO_REPLY','STAFF_REVIEW','OWNER_REVIEW','APPROVAL_REQUIRED')),
  conditions jsonb NOT NULL DEFAULT '{}'::jsonb,
  hard_boundary boolean NOT NULL DEFAULT false,
  enabled boolean NOT NULL DEFAULT true,
  changed_by text NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  previous_version text,
  rollback_reference text,
  rules jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_support_policy_current ON support_policy_versions(enabled, changed_at DESC);
INSERT INTO support_policy_versions (id, policy_version, preset, intent, disposition, conditions, hard_boundary, enabled, changed_by, rules)
VALUES ('9d1f7df2-2f11-4dd6-8b4b-9e47dc0f2d11', 'ai-support-policy-v1', 'STANDARD', 'ALL', 'STAFF_REVIEW', '{"source":"LAB-seed"}', false, true, 'system-lab-seed', '{"hard_boundaries":["MEDICAL_HUMAN_USE_DOSING_RECONSTITUTION","COMPLIANCE","PRIVACY_SECURITY_LEGAL_THREAT"],"presets":["CONSERVATIVE","STANDARD","HIGH"],"intents":{"ORDER_STATUS_REQUEST":"AUTO_RESOLVE","TRACKING_REQUEST":"AUTO_RESOLVE","SHIPPING_ETA":"AUTO_RESOLVE","STORE_POLICY":"AUTO_RESOLVE","PRODUCT_FACT":"AUTO_RESOLVE","STOCK_AVAILABILITY":"AUTO_RESOLVE","COURTESY":"NO_REPLY","HUMAN_REQUEST":"STAFF_REVIEW","DAMAGED_PRODUCT":"STAFF_REVIEW","WRONG_ITEM":"STAFF_REVIEW","MISSING_ITEM":"STAFF_REVIEW","MISSING_SHIPMENT":"STAFF_REVIEW","REFUND":"APPROVAL_REQUIRED","REPLACEMENT":"APPROVAL_REQUIRED","ADDRESS_CHANGE":"APPROVAL_REQUIRED","ORDER_MODIFICATION":"APPROVAL_REQUIRED","CANCELLATION":"APPROVAL_REQUIRED","PAYMENT_ACTION":"APPROVAL_REQUIRED","MEDICAL_HUMAN_USE_DOSING_RECONSTITUTION":"OWNER_REVIEW","COMPLIANCE":"OWNER_REVIEW","PRIVACY_SECURITY_LEGAL_THREAT":"OWNER_REVIEW","LOW_CONFIDENCE":"STAFF_REVIEW","CONFLICTING_DATA":"STAFF_REVIEW","AMBIGUOUS_IDENTITY":"STAFF_REVIEW"}}')
ON CONFLICT (policy_version) DO NOTHING;
